version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  allure: ayte/allure@0.1.3
workflows:
  build:
    jobs:
      # first get the source code and install npm dependencies
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
      