version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  allure: ayte/allure@0.1.3
workflows:
  build:
    jobs:
      # first get the source code and install npm dependencies
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
      - run:
          name: Generate `Allure report` html report
          when: always
          # Run command from orb more info https://github.com/ayte-io/circle-ci-orb-allure
          command: allure generate
      - store_artifacts:
          name: Uploading cypress/videos artifacts
          path: cypress/videos
      - store_artifacts:
          name: Uploading cypress/screenshots artifacts
          path: cypress/screenshots
      - store_artifacts:
          name: Uploading allure-report artifacts
          path: allure-report